name: testthat

on:
  push:
    branches:
      - main
      - adam-dev
      - carina-dev
      - gottfrid-dev
      - pontus-dev
      - '**'
  pull_request:
    branches:
      - main
      - adam-dev
      - carina-dev
      - gottfrid-dev
      - pontus-dev
      - '**'

jobs:
  testthat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
          run: |
            Rscript -e "install.packages(c('devtools','testthat'))"
            Rscript -e "devtools::install_deps(dependencies = TRUE)"

      - name: Run testthat tests
        run: |
          Rscript -e "testthat::test_dir('tests/testthat')"
