name: testthat

on:
  push:
    branches:
      - main
      - adam-dev
      - carina-dev
      - gottfrid-dev
      - pontus-dev
      - '**'
  pull_request:
    branches:
      - main
      - adam-dev
      - carina-dev
      - gottfrid-dev
      - pontus-dev
      - '**'

jobs:
  testthat:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::testthat

      - name: Run testthat tests
        run: |
          Rscript -e "testthat::test_dir('tests/testthat')"
